baseURL: https://confusedbit.dev/
languageCode: en-us
title: Confused bit
theme:
  - "PaperMod"
params:
  custom_css:
    - "css/admonitions.css"
relativeURLs: true
enableEmoji: true
markup:
  goldmark:
    renderer:
      unsafe: true

defaultContentLanguage: en
languages:
  en:
    weight: 1
  fr:
    weight: 2
