baseURL: https://confusedbit.dev/
languageCode: en-us
title: Confused bit
theme:
  - "PaperMod"
params:
  ShowPostNavLinks: true
  custom_css:
    - "css/admonitions.css"
relativeURLs: true
enableEmoji: true
markup:
  goldmark:
    renderer:
      unsafe: true
menu:
  main:
    - identifier: about
      name: About me
      url: /about/
      weight: 10

defaultContentLanguage: en
languages:
  en:
    weight: 1
  fr:
    weight: 2
